# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [25]:
import pandas as pd

df = pd.read_csv("data/AviationData.csv", encoding="latin1")
df.head()

C:\Users\Carro Edeg\AppData\Local\Temp\ipykernel_22032\3066973479.py:3: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/AviationData.csv", encoding="latin1")

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [26]:
# Check the shape of the dataset
df.shape

# Display column names
df.columns

# Check data types and missing values
df.info()

# Summary statistics
df.describe()

# Count missing values
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [27]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nSummary Statistics:")
display(df.describe())

Shape: (88889, 31)

Columns:
Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

Data Types:
Event.Id                   object
Investigation.Type         object
Accident.Number            object
Event.Date                 object
Location                   object
Country                    object
Latitude                   object
Longitude                  object
Airport.Code               object
Airport.Name               object
Injury.Severity            object
Aircraft.damage            object
Aircraft.Category          object
Registration.Number        object
Make                       object
Model                      object
Amateur.Built              object
Number.of.Engines         float64
Engine.Type                object
FAR.Description            object
Schedule                   object
Purpose.of.flight          object
Air.carrier                object
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition          object
Broad.phase.of.flight      object
Report.Status              object
Publication.Date           object
dtype: object

Missing Values:
Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

Summary Statistics:

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [28]:
# Display all column names
df.columns.tolist()

['Event.Id',
 'Investigation.Type',
 'Accident.Number',
 'Event.Date',
 'Location',
 'Country',
 'Latitude',
 'Longitude',
 'Airport.Code',
 'Airport.Name',
 'Injury.Severity',
 'Aircraft.damage',
 'Aircraft.Category',
 'Registration.Number',
 'Make',
 'Model',
 'Amateur.Built',
 'Number.of.Engines',
 'Engine.Type',
 'FAR.Description',
 'Schedule',
 'Purpose.of.flight',
 'Air.carrier',
 'Total.Fatal.Injuries',
 'Total.Serious.Injuries',
 'Total.Minor.Injuries',
 'Total.Uninjured',
 'Weather.Condition',
 'Broad.phase.of.flight',
 'Report.Status',
 'Publication.Date']

In [29]:
df[[
    "Investigation.Type",
    "Aircraft.damage",
    "Injury.Severity",
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]].head()

,Investigation.Type,Aircraft.damage,Injury.Severity,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
0,Accident,Destroyed,Fatal(2),2.0,0.0,0.0,0.0
1,Accident,Destroyed,Fatal(4),4.0,0.0,0.0,0.0
2,Accident,Destroyed,Fatal(3),3.0,NaN,NaN,NaN
3,Accident,Destroyed,Fatal(2),2.0,0.0,0.0,0.0
4,Accident,Destroyed,Fatal(1),1.0,2.0,NaN,0.0

In [30]:
df[[
    "Aircraft.damage",
    "Injury.Severity",
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]].isnull().sum()

Aircraft.damage            3194
Injury.Severity            1000
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
dtype: int64

In [31]:
accidents = df[df["Investigation.Type"] == "Accident"].copy()

accidents.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [32]:
print("Original shape:", df.shape)
print("Filtered shape:", accidents.shape)

Original shape: (88889, 31)
Filtered shape: (85015, 31)

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [33]:
injury_cols = [
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]

accidents[injury_cols] = accidents[injury_cols].fillna(0)

# Estimate total passengers
accidents["Total.Passengers"] = (
    accidents["Total.Fatal.Injuries"]
    + accidents["Total.Serious.Injuries"]
    + accidents["Total.Minor.Injuries"]
    + accidents["Total.Uninjured"]
)

# Total serious or fatal injuries
accidents["Serious.Fatal"] = (
    accidents["Total.Fatal.Injuries"]
    + accidents["Total.Serious.Injuries"]
)

# Injury rate
accidents["Serious.Fatal.Rate"] = (
    accidents["Serious.Fatal"] /
    accidents["Total.Passengers"].replace(0, pd.NA)
)

accidents[[
    "Total.Passengers",
    "Serious.Fatal",
    "Serious.Fatal.Rate"
]].head()

   Total.Passengers  Serious.Fatal Serious.Fatal.Rate
0               2.0            2.0                1.0
1               4.0            4.0                1.0
2               3.0            3.0                1.0
3               2.0            2.0                1.0
4               3.0            3.0                1.0

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [34]:
accidents["Aircraft.damage"].value_counts(dropna=False)

Aircraft.damage
Substantial    64106
Destroyed      18615
NaN             1460
Minor            737
Unknown           97
Name: count, dtype: int64

In [35]:
accidents["Destroyed"] = (
    accidents["Aircraft.damage"]
    .fillna("Unknown")
    .eq("Destroyed")
)

accidents[["Aircraft.damage", "Destroyed"]].head()

  Aircraft.damage  Destroyed
0       Destroyed       True
1       Destroyed       True
2       Destroyed       True
3       Destroyed       True
4       Destroyed       True

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [36]:
accidents["Make"].value_counts().head(20)

Make
Cessna         21973
Piper          11885
CESSNA          4820
Beech           4170
PIPER           2799
Bell            2093
Grumman         1080
Mooney          1074
BEECH           1007
Robinson         943
Boeing           916
Bellanca         883
Hughes           790
Schweizer        627
Air Tractor      593
BELL             569
Aeronca          484
BOEING           446
Maule            443
Champion         427
Name: count, dtype: int64

In [37]:
make_counts = accidents["Make"].value_counts()

make_counts.head(20)

Make
Cessna         21973
Piper          11885
CESSNA          4820
Beech           4170
PIPER           2799
Bell            2093
Grumman         1080
Mooney          1074
BEECH           1007
Robinson         943
Boeing           916
Bellanca         883
Hughes           790
Schweizer        627
Air Tractor      593
BELL             569
Aeronca          484
BOEING           446
Maule            443
Champion         427
Name: count, dtype: int64

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [38]:
# Remove rows where Make or Model is missing
accidents = accidents.dropna(subset=["Make", "Model"]).copy()

# Clean extra spaces and standardize capitalization
accidents["Make"] = accidents["Make"].str.strip().str.title()
accidents["Model"] = accidents["Model"].str.strip().str.upper()

# Inspect common models
accidents[["Make", "Model"]].value_counts().head(20)

Make    Model
Cessna  152          2348
        172          1744
        172N         1160
Piper   PA-28-140     929
Cessna  150           822
        172M          793
        172P          685
        182           653
        180           620
        150M          583
Piper   PA-18         578
        PA-18-150     571
        PA-28-180     571
        PA-28-161     561
        PA-28-181     525
Bell    206B          514
Piper   PA-38-112     464
Cessna  150L          458
Beech   A36           415
Cessna  140           401
Name: count, dtype: int64

In [39]:
# Combine Make and Model to identify each aircraft type
accidents["Aircraft.Type"] = (
    accidents["Make"] + " " + accidents["Model"]
)

accidents[["Make", "Model", "Aircraft.Type"]].head()

       Make     Model   Aircraft.Type
0   Stinson     108-3   Stinson 108-3
1     Piper  PA24-180  Piper PA24-180
2    Cessna      172M     Cessna 172M
3  Rockwell       112    Rockwell 112
4    Cessna       501      Cessna 501

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [40]:
other_columns = [
    "Engine.Type",
    "Weather.Condition",
    "Number.of.Engines",
    "Purpose.of.flight",
    "Broad.phase.of.flight"
]

# Inspect missing values
accidents[other_columns].isna().sum()

Engine.Type               5821
Weather.Condition         3106
Number.of.Engines         4870
Purpose.of.flight         4305
Broad.phase.of.flight    25170
dtype: int64

In [41]:
text_columns = [
    "Engine.Type",
    "Weather.Condition",
    "Purpose.of.flight",
    "Broad.phase.of.flight"
]

for column in text_columns:
    accidents[column] = (
        accidents[column]
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
    )

# Convert number of engines to numeric
accidents["Number.of.Engines"] = pd.to_numeric(
    accidents["Number.of.Engines"],
    errors="coerce"
)

accidents[other_columns].head()

,Engine.Type,Weather.Condition,Number.of.Engines,Purpose.of.flight,Broad.phase.of.flight
0,Reciprocating,UNK,1.0,Personal,Cruise
1,Reciprocating,UNK,1.0,Personal,Unknown
2,Reciprocating,IMC,1.0,Personal,Cruise
3,Reciprocating,IMC,1.0,Personal,Cruise
4,<NA>,VMC,NaN,Personal,Approach

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [42]:
# Percentage of missing values in each column
missing_percent = accidents.isnull().mean() * 100

missing_percent.sort_values(ascending=False)

Schedule                  88.133558
Air.carrier               82.751922
FAR.Description           64.313550
Aircraft.Category         64.093387
Longitude                 60.716767
Latitude                  60.706170
Airport.Code              43.309747
Airport.Name              40.376985
Broad.phase.of.flight     29.633729
Publication.Date          15.379634
Engine.Type                6.853315
Report.Status              6.138667
Number.of.Engines          5.733661
Purpose.of.flight          5.068463
Weather.Condition          3.656828
Aircraft.damage            1.717744
Registration.Number        1.282127
Serious.Fatal.Rate         0.523918
Injury.Severity            0.381459
Country                    0.242533
Amateur.Built              0.065931
Location                   0.047094
Total.Passengers           0.000000
Serious.Fatal              0.000000
Total.Uninjured            0.000000
Destroyed                  0.000000
Event.Id                   0.000000
Total.Minor.Injuries       0.000000
Total.Serious.Injuries     0.000000
Total.Fatal.Injuries       0.000000
Investigation.Type         0.000000
Model                      0.000000
Make                       0.000000
Event.Date                 0.000000
Accident.Number            0.000000
Aircraft.Type              0.000000
dtype: float64

In [43]:
# Drop columns with more than 70% missing values
cols_to_drop = missing_percent[missing_percent > 70].index

accidents = accidents.drop(columns=cols_to_drop)

print("Dropped columns:")
print(cols_to_drop.tolist())

print("\nRemaining shape:", accidents.shape)

Dropped columns:
['Schedule', 'Air.carrier']

Remaining shape: (84937, 34)

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [44]:
accidents.to_csv("data/cleaned_aviation_accidents.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!